// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {context} from '../models';

export function DropTable(arg1:string):Promise<void>;

export function ListSchemas():Promise<Array<string>>;

export function ListTables():Promise<Array<string>>;

export function Query(arg1:string):Promise<database.Results>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TruncateTable(arg1:string):Promise<void>;

export function Use(arg1:string):Promise<void>;
