// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DropTable(arg1) {
  return window['go']['main']['Adapter']['DropTable'](arg1);
}

export function ListSchemas() {
  return window['go']['main']['Adapter']['ListSchemas']();
}

export function ListTables() {
  return window['go']['main']['Adapter']['ListTables']();
}

export function Query(arg1) {
  return window['go']['main']['Adapter']['Query'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['Adapter']['SetContext'](arg1);
}

export function TruncateTable(arg1) {
  return window['go']['main']['Adapter']['TruncateTable'](arg1);
}

export function Use(arg1) {
  return window['go']['main']['Adapter']['Use'](arg1);
}
