// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ListSchemas() {
  return window['go']['main']['App']['ListSchemas']();
}

export function ListTables() {
  return window['go']['main']['App']['ListTables']();
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function RunTableCommand(arg1, arg2) {
  return window['go']['main']['App']['RunTableCommand'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function TableCommands() {
  return window['go']['main']['App']['TableCommands']();
}

export function Use(arg1) {
  return window['go']['main']['App']['Use'](arg1);
}
